---
- project:
    name: packit-servie-deployment
    check:
      jobs:
        - packit-service-deployment
    gate:
      jobs:
        - packit-service-deployment

- job:
    name: packit-service-deployment
    allowed-projects:
    - packit-service/packit-service
    final: true # this prevent job modification
    run: files/deploy-service.yaml
    cleanup-run: files/cleanup.yaml
