---
- name: Install packages
  dnf:
    name:
      - git-core
      - python36
      - python37
      - python38
      - pre-commit
  become: true

- name: Run 'pre-commit install' to set up git hook scripts
  command: pre-commit install
  args:
    chdir: "{{ zuul.project.src_dir }}"

- name: Run pre-commit
  command: pre-commit run --all-files
  args:
    chdir: "{{ zuul.project.src_dir }}"
