---
- name: Destroy packit-service objects in OpenShift
  hosts: all
  tasks:
  - name: Cleanup the cluster objects
    command: oc delete all --all
    environment:
      ANSIBLE_STDOUT_CALLBACK: debug
    become: true

  - name: Cleanup the secrets
    command: oc delete secrets --all
    environment:
      ANSIBLE_STDOUT_CALLBACK: debug
    become: true
