
- secret:
    name: ssh_config
    data:
      value: !encrypted/pkcs1-oaep
        - S/vuCvytyF7UlXQzbbocOvlCyA8R8rrkzvu/uHeQuKBP6KdjKeFJK9Vvw60u+QTh/CMaB
          LnpOPERDsqRSzT7sAWGtwVwm912fYI+REdH8b6i+6E8jqjG/h5PT8b5Cs22L3xxRRJwjX
          iIThDaFOGkZpk5KUiLnltWtHZwr75tXdR9/HnknmgujnXY2gK3mNwBqXhFr9/0NLFmNpJ
          ojTaP5borra5BDNpVedgY9Vf8XPXE5ZCMDc7+YyzwRARgM4mXf5zinHnGw6BdhxHwlQFF
          yZEv/LQjusONi9mrwyok7QimLdjf4DK4RWgjX4ZZ9N1XcDypetAwbkBT1v1CIKsIZp3JD
          Jy/+I7J3E2DpTqHG1bOqvQKQyGpG3J7qermhD+WnomNrsXEYib6XUjTwk99mp7hYn8k0Y
          QTh8UbY2GhGSLtpWEzmJ2SJ8mjKuyAtES8l916SknO/FYzbm4YJeK/IJL0tQA0loaqwLs
          9yEqnqaaV7HqOyu2hgQPWQjqb3WDBdsDUp6sNfPSgvO/L/7+uf5PThbJ951lbJRe1ZtCw
          mcAga2NNFPwqhHtrk4n28YlWOAfyJlqHVpfXIzcf2PiALh5glWUxYgB8uRdQ3vEtgg0Ve
          5e0An9msgvTyiY9GGx9XL2cVAAENATyo/FOcJQALJWb82YdgB8bAt+cPDktEWY=
