
- secret:
    name: ssh_config
    data:
      value: !encrypted/pkcs1-oaep
        - E9JVwpI9l8eyYtclWzm8tgH9411qVJ0AFnv4WO+nxd9PsIPjytNG4CyjmgJE2LvZgxe+J
          mowlpmm19fWcI1sPgbp2yFUw0hkCQvKDINdMBbXIgV+kcPmwz2UADQ+1ZpUnESe0YxAnY
          z9MMOJaiDBD0s2sAdP66qGbvnoi8K3kslVyuGyZ6sPRAWKOM+v2NGg7ejLqV9suRGgwBv
          VOPut/hxmrI0OhLH09tTjFjZxEXHmxSrgD6qXy2nNOMkAcedUR+Uo+1UByRbrIwP46c+p
          VODGZwbo2LV9Sb6f9EV0JSujWFpJh9MSM3CjEC3uNgoaCLz/86dDnk6DxA77sYJxiUDkq
          rtPepz+bMw/pYeH0IpiEXR+bXXgXmKiH7P5bCYqhgG43Nba44jc/RcpYhdDCjWM9dSt87
          8a6VEhFb0rE44h3odZfOiaC7jBVPkOWQ8Esj+4FQXbUAZFxpbFaQk9Hu4fQscU+E/Olzn
          m5TSAnX/pNP40+NmHwPWVunRhF2iukp9mQOxuWtwWXS/UNBdcl0eWmC/Gm57H/pKzvSQO
          tQ4wencu3EQn8LXBH3cKR5oQXkTU1N6bpD7Ba8oa7IPXBN6xHeUp3R+Pt551PYYIjdtDr
          /I6vEDfEIjJC0APMR9PkgLOnWfMjWuOjy7xDWDKkpuhNuncuU7ZKE3Cd1NTmxQ=
